CREATE TABLE shelters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (btrim(name) <> ''),
    address VARCHAR(300) NOT NULL CHECK (btrim(address) <> '')
);
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (btrim(name) <> ''),
    email VARCHAR(254) NOT NULL UNIQUE CHECK (btrim(email) <> ''),
    role VARCHAR(30) NOT NULL CHECK (role IN ('APPLICANT', 'VOLUNTEER', 'EMPLOYEE', 'SUPERVISOR')),
    shelter_id BIGINT REFERENCES shelters(id),
    CHECK (role <> 'EMPLOYEE' OR shelter_id IS NOT NULL)
);
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE CHECK (btrim(name) <> '')
);
CREATE TABLE animals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_id BIGINT NOT NULL REFERENCES shelters(id),
    name VARCHAR(120) NOT NULL CHECK (btrim(name) <> ''),
    species VARCHAR(20) NOT NULL CHECK (species IN ('CAT', 'DOG', 'OTHER')),
    birth_date DATE NOT NULL,
    description VARCHAR(2000) NOT NULL CHECK (btrim(description) <> ''),
    status VARCHAR(20) NOT NULL CHECK (status IN ('AVAILABLE', 'ADOPTED'))
);
CREATE TABLE animal_tags (
    animal_id BIGINT NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (animal_id, tag_id)
);
CREATE TABLE adoption_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id BIGINT NOT NULL REFERENCES animals(id),
    applicant_id BIGINT NOT NULL REFERENCES users(id),
    comment VARCHAR(2000) NOT NULL CHECK (btrim(comment) <> ''),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'COMPLETED')),
    created_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX uq_active_application ON adoption_applications (animal_id, applicant_id)
    WHERE status IN ('PENDING', 'APPROVED');
CREATE UNIQUE INDEX uq_approved_application ON adoption_applications (animal_id) WHERE status = 'APPROVED';
CREATE UNIQUE INDEX uq_completed_application ON adoption_applications (animal_id) WHERE status = 'COMPLETED';
CREATE TABLE volunteer_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_id BIGINT NOT NULL REFERENCES shelters(id),
    title VARCHAR(160) NOT NULL CHECK (btrim(title) <> ''),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity BETWEEN 1 AND 1000),
    status VARCHAR(20) NOT NULL CHECK (status IN ('SCHEDULED', 'CANCELLED')),
    CHECK (ends_at > starts_at)
);
CREATE TABLE shift_participations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT NOT NULL REFERENCES volunteer_shifts(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('REGISTERED', 'CANCELLED')),
    registered_at TIMESTAMPTZ NOT NULL,
    UNIQUE (shift_id, user_id)
);
CREATE INDEX ix_users_shelter ON users(shelter_id);
CREATE INDEX ix_animals_shelter_status ON animals(shelter_id, status, id);
CREATE INDEX ix_animal_tags_tag ON animal_tags(tag_id);
CREATE INDEX ix_applications_applicant ON adoption_applications(applicant_id, id);
CREATE INDEX ix_applications_animal_status ON adoption_applications(animal_id, status);
CREATE INDEX ix_shifts_shelter_status ON volunteer_shifts(shelter_id, status, id);
CREATE INDEX ix_participations_shift_status ON shift_participations(shift_id, status);
CREATE INDEX ix_participations_user ON shift_participations(user_id);
